\echo 'Initializing text-to-SQL demo schemas, roles, views, fixtures, and metrics'

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS', :'raw_role', :'raw_role_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'raw_role') \gexec
SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS', :'views_role', :'views_role_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'views_role') \gexec

-- RDS master users cannot alter SUPERUSER/BYPASSRLS attributes. New roles are
-- created least-privilege above; reruns only need to refresh passwords.
ALTER ROLE :"raw_role" WITH LOGIN PASSWORD :'raw_role_password';
ALTER ROLE :"views_role" WITH LOGIN PASSWORD :'views_role_password';

CREATE SCHEMA IF NOT EXISTS raw_app;
CREATE SCHEMA IF NOT EXISTS analytics_app;
CREATE SCHEMA IF NOT EXISTS demo_app;

CREATE TABLE IF NOT EXISTS raw_app.tenants (
    id text PRIMARY KEY,
    name text NOT NULL,
    region text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw_app.customer_segments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    name text NOT NULL,
    margin_tier text NOT NULL,
    lifecycle_stage text NOT NULL,
    UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS raw_app.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    segment_id integer NOT NULL REFERENCES raw_app.customer_segments(id),
    external_ref text NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    phone text,
    acquisition_channel text NOT NULL,
    signup_date date NOT NULL,
    status text NOT NULL,
    UNIQUE (tenant_id, email)
);

CREATE TABLE IF NOT EXISTS raw_app.customer_addresses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES raw_app.customers(id),
    address_type text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    country text NOT NULL,
    postal_code text NOT NULL,
    is_default boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS raw_app.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id integer REFERENCES raw_app.categories(id),
    name text NOT NULL,
    merchandising_owner text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    country text NOT NULL,
    reliability_score numeric(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer NOT NULL REFERENCES raw_app.categories(id),
    supplier_id integer NOT NULL REFERENCES raw_app.suppliers(id),
    sku text NOT NULL UNIQUE,
    name text NOT NULL,
    brand text NOT NULL,
    list_price numeric(12,2) NOT NULL,
    standard_cost numeric(12,2) NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS raw_app.warehouses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    region text NOT NULL,
    city text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.inventory_snapshots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES raw_app.products(id),
    warehouse_id integer NOT NULL REFERENCES raw_app.warehouses(id),
    snapshot_date date NOT NULL,
    on_hand integer NOT NULL,
    allocated integer NOT NULL,
    reorder_point integer NOT NULL,
    UNIQUE (product_id, warehouse_id, snapshot_date)
);

CREATE TABLE IF NOT EXISTS raw_app.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    customer_id integer NOT NULL REFERENCES raw_app.customers(id),
    order_number text NOT NULL UNIQUE,
    order_ts timestamptz NOT NULL,
    status text NOT NULL,
    currency text NOT NULL,
    subtotal_amount numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) NOT NULL,
    tax_amount numeric(12,2) NOT NULL,
    shipping_amount numeric(12,2) NOT NULL,
    total_amount numeric(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.order_lines (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES raw_app.orders(id),
    product_id integer NOT NULL REFERENCES raw_app.products(id),
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    unit_cost numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES raw_app.orders(id),
    payment_ts timestamptz NOT NULL,
    payment_method text NOT NULL,
    status text NOT NULL,
    processor text NOT NULL,
    amount numeric(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.shipments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES raw_app.orders(id),
    warehouse_id integer NOT NULL REFERENCES raw_app.warehouses(id),
    carrier text NOT NULL,
    shipped_ts timestamptz,
    delivered_ts timestamptz,
    status text NOT NULL,
    shipping_cost numeric(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    customer_id integer NOT NULL REFERENCES raw_app.customers(id),
    product_id integer NOT NULL REFERENCES raw_app.products(id),
    rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_ts timestamptz NOT NULL,
    sentiment text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.promotions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    channel text NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    discount_type text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.order_promotions (
    order_id integer NOT NULL REFERENCES raw_app.orders(id),
    promotion_id integer NOT NULL REFERENCES raw_app.promotions(id),
    discount_amount numeric(12,2) NOT NULL,
    PRIMARY KEY (order_id, promotion_id)
);

CREATE TABLE IF NOT EXISTS raw_app.support_tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    customer_id integer NOT NULL REFERENCES raw_app.customers(id),
    order_id integer REFERENCES raw_app.orders(id),
    opened_ts timestamptz NOT NULL,
    closed_ts timestamptz,
    priority text NOT NULL,
    topic text NOT NULL,
    status text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.ticket_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES raw_app.support_tickets(id),
    event_ts timestamptz NOT NULL,
    event_type text NOT NULL,
    actor_type text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.marketing_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    customer_id integer REFERENCES raw_app.customers(id),
    event_ts timestamptz NOT NULL,
    campaign text NOT NULL,
    channel text NOT NULL,
    event_type text NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_app.web_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id text NOT NULL REFERENCES raw_app.tenants(id),
    customer_id integer REFERENCES raw_app.customers(id),
    started_ts timestamptz NOT NULL,
    device_type text NOT NULL,
    landing_page text NOT NULL,
    converted_order_id integer REFERENCES raw_app.orders(id)
);

CREATE INDEX IF NOT EXISTS idx_raw_customers_tenant ON raw_app.customers (tenant_id);
CREATE INDEX IF NOT EXISTS idx_raw_orders_tenant_ts ON raw_app.orders (tenant_id, order_ts);
CREATE INDEX IF NOT EXISTS idx_raw_orders_customer ON raw_app.orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_raw_order_lines_order ON raw_app.order_lines (order_id);
CREATE INDEX IF NOT EXISTS idx_raw_order_lines_product ON raw_app.order_lines (product_id);
CREATE INDEX IF NOT EXISTS idx_raw_payments_order ON raw_app.payments (order_id);
CREATE INDEX IF NOT EXISTS idx_raw_shipments_order ON raw_app.shipments (order_id);
CREATE INDEX IF NOT EXISTS idx_raw_reviews_product ON raw_app.reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_raw_tickets_customer ON raw_app.support_tickets (customer_id);

TRUNCATE TABLE
    raw_app.ticket_events,
    raw_app.support_tickets,
    raw_app.web_sessions,
    raw_app.marketing_events,
    raw_app.order_promotions,
    raw_app.promotions,
    raw_app.reviews,
    raw_app.shipments,
    raw_app.payments,
    raw_app.order_lines,
    raw_app.orders,
    raw_app.inventory_snapshots,
    raw_app.products,
    raw_app.warehouses,
    raw_app.suppliers,
    raw_app.categories,
    raw_app.customer_addresses,
    raw_app.customers,
    raw_app.customer_segments,
    raw_app.tenants
RESTART IDENTITY CASCADE;

INSERT INTO raw_app.tenants (id, name, region)
VALUES
    ('tenant-a', 'Northwind Premium', 'NA'),
    ('tenant-b', 'Contoso Direct', 'EU');

INSERT INTO raw_app.customer_segments (tenant_id, name, margin_tier, lifecycle_stage)
SELECT tenant_id, segment_name, margin_tier, lifecycle_stage
FROM (
    VALUES
        ('tenant-a', 'Enterprise', 'high', 'growth'),
        ('tenant-a', 'SMB', 'medium', 'retention'),
        ('tenant-a', 'Consumer', 'low', 'activation'),
        ('tenant-b', 'Enterprise', 'high', 'growth'),
        ('tenant-b', 'SMB', 'medium', 'retention'),
        ('tenant-b', 'Consumer', 'low', 'activation')
) AS seed(tenant_id, segment_name, margin_tier, lifecycle_stage);

INSERT INTO raw_app.customers (tenant_id, segment_id, external_ref, full_name, email, phone, acquisition_channel, signup_date, status)
SELECT
    CASE WHEN i % 2 = 0 THEN 'tenant-a' ELSE 'tenant-b' END,
    cs.id,
    'CUST-' || lpad(i::text, 5, '0'),
    'Customer ' || i,
    'customer' || i || '@example.test',
    '+1-555-' || lpad((1000 + i)::text, 4, '0'),
    (ARRAY['paid_search', 'organic', 'partner', 'email', 'field_sales'])[1 + (i % 5)],
    current_date - ((i % 540) || ' days')::interval,
    CASE WHEN i % 17 = 0 THEN 'inactive' ELSE 'active' END
FROM generate_series(1, 160 * :seed_scale_factor) AS g(i)
JOIN raw_app.customer_segments AS cs
  ON cs.tenant_id = CASE WHEN i % 2 = 0 THEN 'tenant-a' ELSE 'tenant-b' END
 AND cs.name = (ARRAY['Enterprise', 'SMB', 'Consumer'])[1 + (i % 3)];

INSERT INTO raw_app.customer_addresses (customer_id, address_type, city, state, country, postal_code, is_default)
SELECT
    id,
    'billing',
    (ARRAY['Amsterdam', 'New York', 'Berlin', 'Austin', 'London', 'Paris'])[1 + (id % 6)],
    (ARRAY['NH', 'NY', 'BE', 'TX', 'LDN', 'IDF'])[1 + (id % 6)],
    CASE WHEN tenant_id = 'tenant-a' THEN 'US' ELSE 'NL' END,
    lpad((10000 + id)::text, 5, '0'),
    true
FROM raw_app.customers;

INSERT INTO raw_app.categories (parent_id, name, merchandising_owner)
VALUES
    (NULL, 'Electronics', 'Ava'),
    (NULL, 'Home', 'Noah'),
    (NULL, 'Outdoor', 'Mia'),
    (NULL, 'Software', 'Liam'),
    (1, 'Laptops', 'Ava'),
    (1, 'Accessories', 'Ava'),
    (2, 'Kitchen', 'Noah'),
    (3, 'Cycling', 'Mia'),
    (4, 'Subscriptions', 'Liam');

INSERT INTO raw_app.suppliers (name, country, reliability_score)
SELECT
    'Supplier ' || i,
    (ARRAY['US', 'NL', 'DE', 'GB', 'CA'])[1 + (i % 5)],
    round((82 + (i % 17) + (i % 3) * 0.25)::numeric, 2)
FROM generate_series(1, 12) AS g(i);

INSERT INTO raw_app.products (category_id, supplier_id, sku, name, brand, list_price, standard_cost, active)
SELECT
    1 + (i % 9),
    1 + (i % 12),
    'SKU-' || lpad(i::text, 5, '0'),
    'Product ' || i,
    (ARRAY['North', 'Beacon', 'Summit', 'Orbit', 'Vector'])[1 + (i % 5)],
    round((20 + (i % 90) * 3.71)::numeric, 2),
    round((10 + (i % 80) * 2.04)::numeric, 2),
    i % 29 <> 0
FROM generate_series(1, 80 * :seed_scale_factor) AS g(i);

INSERT INTO raw_app.warehouses (code, region, city)
VALUES
    ('EAST-1', 'NA', 'Newark'),
    ('WEST-1', 'NA', 'Reno'),
    ('EU-1', 'EU', 'Rotterdam'),
    ('EU-2', 'EU', 'Berlin');

INSERT INTO raw_app.inventory_snapshots (product_id, warehouse_id, snapshot_date, on_hand, allocated, reorder_point)
SELECT
    p.id,
    w.id,
    current_date,
    20 + ((p.id * w.id) % 240),
    (p.id + w.id) % 35,
    15 + (p.id % 20)
FROM raw_app.products AS p
CROSS JOIN raw_app.warehouses AS w;

WITH order_seed AS (
    SELECT
        i,
        c.id AS customer_id,
        c.tenant_id,
        (current_date - ((i % 180) || ' days')::interval + ((i % 24) || ' hours')::interval) AS order_ts,
        (ARRAY['paid', 'paid', 'paid', 'paid', 'refunded', 'cancelled'])[1 + (i % 6)] AS status,
        round((35 + (i % 250) * 4.65)::numeric, 2) AS subtotal,
        round(((i % 4) * 3.25)::numeric, 2) AS discount,
        round((3 + (i % 30) * 0.58)::numeric, 2) AS tax,
        round((5 + (i % 7) * 1.15)::numeric, 2) AS shipping
    FROM generate_series(1, 640 * :seed_scale_factor) AS g(i)
    JOIN raw_app.customers AS c
      ON c.id = 1 + (i % (SELECT count(*) FROM raw_app.customers))
)
INSERT INTO raw_app.orders (tenant_id, customer_id, order_number, order_ts, status, currency, subtotal_amount, discount_amount, tax_amount, shipping_amount, total_amount)
SELECT
    tenant_id,
    customer_id,
    'ORD-' || lpad(i::text, 7, '0'),
    order_ts,
    status,
    'USD',
    subtotal,
    discount,
    tax,
    shipping,
    subtotal - discount + tax + shipping
FROM order_seed;

INSERT INTO raw_app.order_lines (order_id, product_id, quantity, unit_price, unit_cost, discount_amount)
SELECT
    o.id,
    1 + ((o.id + line_no * 13) % (SELECT count(*) FROM raw_app.products)),
    1 + ((o.id + line_no) % 4),
    round((12 + ((o.id + line_no) % 130) * 2.33)::numeric, 2),
    round((6 + ((o.id + line_no) % 100) * 1.41)::numeric, 2),
    round((((o.id + line_no) % 5) * 1.25)::numeric, 2)
FROM raw_app.orders AS o
CROSS JOIN generate_series(1, 2) AS line(line_no);

INSERT INTO raw_app.payments (order_id, payment_ts, payment_method, status, processor, amount)
SELECT
    id,
    order_ts + interval '5 minutes',
    (ARRAY['card', 'ach', 'paypal', 'apple_pay'])[1 + (id % 4)],
    CASE WHEN status = 'cancelled' THEN 'failed' WHEN id % 23 = 0 THEN 'failed' ELSE 'completed' END,
    (ARRAY['stripe', 'adyen', 'braintree'])[1 + (id % 3)],
    total_amount
FROM raw_app.orders;

INSERT INTO raw_app.shipments (order_id, warehouse_id, carrier, shipped_ts, delivered_ts, status, shipping_cost)
SELECT
    id,
    1 + (id % 4),
    (ARRAY['ups', 'fedex', 'dhl', 'local'])[1 + (id % 4)],
    CASE WHEN status IN ('paid', 'refunded') THEN order_ts + interval '1 day' ELSE NULL END,
    CASE WHEN status = 'paid' THEN order_ts + ((2 + (id % 6)) || ' days')::interval ELSE NULL END,
    CASE WHEN status = 'cancelled' THEN 'cancelled' WHEN id % 19 = 0 THEN 'delayed' ELSE 'delivered' END,
    shipping_amount * 0.72
FROM raw_app.orders;

INSERT INTO raw_app.reviews (tenant_id, customer_id, product_id, rating, review_ts, sentiment)
SELECT
    c.tenant_id,
    c.id,
    1 + ((c.id + i * 7) % (SELECT count(*) FROM raw_app.products)),
    1 + ((c.id + i) % 5),
    current_date - ((i % 90) || ' days')::interval,
    (ARRAY['negative', 'neutral', 'positive', 'positive', 'positive'])[1 + ((c.id + i) % 5)]
FROM generate_series(1, 220 * :seed_scale_factor) AS g(i)
JOIN raw_app.customers AS c
  ON c.id = 1 + (i % (SELECT count(*) FROM raw_app.customers));

INSERT INTO raw_app.promotions (code, channel, starts_on, ends_on, discount_type)
VALUES
    ('WELCOME10', 'email', current_date - 120, current_date + 120, 'percent'),
    ('FREESHIP', 'onsite', current_date - 90, current_date + 60, 'shipping'),
    ('VIP25', 'sales', current_date - 60, current_date + 30, 'percent'),
    ('BUNDLE15', 'paid_search', current_date - 45, current_date + 45, 'fixed'),
    ('WINBACK', 'email', current_date - 30, current_date + 90, 'percent');

INSERT INTO raw_app.order_promotions (order_id, promotion_id, discount_amount)
SELECT
    id,
    1 + (id % 5),
    round((2 + (id % 11) * 1.15)::numeric, 2)
FROM raw_app.orders
WHERE id % 7 = 0;

INSERT INTO raw_app.support_tickets (tenant_id, customer_id, order_id, opened_ts, closed_ts, priority, topic, status)
SELECT
    c.tenant_id,
    c.id,
    o.id,
    o.order_ts + interval '2 days',
    CASE WHEN i % 5 = 0 THEN NULL ELSE o.order_ts + interval '4 days' END,
    (ARRAY['low', 'medium', 'high', 'urgent'])[1 + (i % 4)],
    (ARRAY['shipping', 'payment', 'return', 'product_quality', 'account'])[1 + (i % 5)],
    CASE WHEN i % 5 = 0 THEN 'open' ELSE 'closed' END
FROM generate_series(1, 140 * :seed_scale_factor) AS g(i)
JOIN raw_app.orders AS o ON o.id = 1 + (i % (SELECT count(*) FROM raw_app.orders))
JOIN raw_app.customers AS c ON c.id = o.customer_id;

INSERT INTO raw_app.ticket_events (ticket_id, event_ts, event_type, actor_type)
SELECT
    t.id,
    t.opened_ts + ((event_no - 1) || ' hours')::interval,
    CASE WHEN event_no = 1 THEN 'opened' ELSE 'agent_reply' END,
    CASE WHEN event_no = 1 THEN 'customer' ELSE 'agent' END
FROM raw_app.support_tickets AS t
CROSS JOIN generate_series(1, 2) AS ev(event_no);

INSERT INTO raw_app.marketing_events (tenant_id, customer_id, event_ts, campaign, channel, event_type)
SELECT
    c.tenant_id,
    c.id,
    current_date - ((i % 120) || ' days')::interval,
    (ARRAY['spring_launch', 'retention_q2', 'vip_upsell', 'winback'])[1 + (i % 4)],
    (ARRAY['email', 'paid_search', 'organic', 'partner'])[1 + (i % 4)],
    (ARRAY['impression', 'click', 'signup', 'purchase'])[1 + (i % 4)]
FROM generate_series(1, 520 * :seed_scale_factor) AS g(i)
JOIN raw_app.customers AS c
  ON c.id = 1 + (i % (SELECT count(*) FROM raw_app.customers));

INSERT INTO raw_app.web_sessions (tenant_id, customer_id, started_ts, device_type, landing_page, converted_order_id)
SELECT
    c.tenant_id,
    c.id,
    current_date - ((i % 60) || ' days')::interval + ((i % 24) || ' hours')::interval,
    (ARRAY['desktop', 'mobile', 'tablet'])[1 + (i % 3)],
    (ARRAY['/', '/collections', '/pricing', '/campaign'])[1 + (i % 4)],
    CASE WHEN i % 6 = 0 THEN o.id ELSE NULL END
FROM generate_series(1, 420 * :seed_scale_factor) AS g(i)
JOIN raw_app.customers AS c
  ON c.id = 1 + (i % (SELECT count(*) FROM raw_app.customers))
LEFT JOIN raw_app.orders AS o
  ON o.customer_id = c.id
 AND o.id = 1 + (i % (SELECT count(*) FROM raw_app.orders));

ALTER TABLE raw_app.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.customer_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.inventory_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.order_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.ticket_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.marketing_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_app.web_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_scope ON raw_app.tenants;
DROP POLICY IF EXISTS tenant_scope ON raw_app.customer_segments;
DROP POLICY IF EXISTS tenant_scope ON raw_app.customers;
DROP POLICY IF EXISTS tenant_scope ON raw_app.customer_addresses;
DROP POLICY IF EXISTS tenant_scope ON raw_app.categories;
DROP POLICY IF EXISTS tenant_scope ON raw_app.suppliers;
DROP POLICY IF EXISTS tenant_scope ON raw_app.products;
DROP POLICY IF EXISTS tenant_scope ON raw_app.warehouses;
DROP POLICY IF EXISTS tenant_scope ON raw_app.inventory_snapshots;
DROP POLICY IF EXISTS tenant_scope ON raw_app.orders;
DROP POLICY IF EXISTS tenant_scope ON raw_app.order_lines;
DROP POLICY IF EXISTS tenant_scope ON raw_app.payments;
DROP POLICY IF EXISTS tenant_scope ON raw_app.shipments;
DROP POLICY IF EXISTS tenant_scope ON raw_app.reviews;
DROP POLICY IF EXISTS tenant_scope ON raw_app.promotions;
DROP POLICY IF EXISTS tenant_scope ON raw_app.order_promotions;
DROP POLICY IF EXISTS tenant_scope ON raw_app.support_tickets;
DROP POLICY IF EXISTS tenant_scope ON raw_app.ticket_events;
DROP POLICY IF EXISTS tenant_scope ON raw_app.marketing_events;
DROP POLICY IF EXISTS tenant_scope ON raw_app.web_sessions;

CREATE POLICY tenant_scope ON raw_app.tenants FOR SELECT TO :"raw_role"
USING (id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.customer_segments FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.customers FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.customer_addresses FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.customers AS c
        WHERE c.id = raw_app.customer_addresses.customer_id
          AND c.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.orders FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.order_lines FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.orders AS o
        WHERE o.id = raw_app.order_lines.order_id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.payments FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.orders AS o
        WHERE o.id = raw_app.payments.order_id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.shipments FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.orders AS o
        WHERE o.id = raw_app.shipments.order_id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.reviews FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.support_tickets FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.ticket_events FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.support_tickets AS t
        WHERE t.id = raw_app.ticket_events.ticket_id
          AND t.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.marketing_events FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.web_sessions FOR SELECT TO :"raw_role"
USING (tenant_id = current_setting('app.tenant_id', true));

CREATE POLICY tenant_scope ON raw_app.products FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.order_lines AS ol
        JOIN raw_app.orders AS o ON o.id = ol.order_id
        WHERE ol.product_id = raw_app.products.id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.categories FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.products AS p
        JOIN raw_app.order_lines AS ol ON ol.product_id = p.id
        JOIN raw_app.orders AS o ON o.id = ol.order_id
        WHERE p.category_id = raw_app.categories.id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.suppliers FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.products AS p
        JOIN raw_app.order_lines AS ol ON ol.product_id = p.id
        JOIN raw_app.orders AS o ON o.id = ol.order_id
        WHERE p.supplier_id = raw_app.suppliers.id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.warehouses FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.shipments AS s
        JOIN raw_app.orders AS o ON o.id = s.order_id
        WHERE s.warehouse_id = raw_app.warehouses.id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.inventory_snapshots FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.products AS p
        JOIN raw_app.order_lines AS ol ON ol.product_id = p.id
        JOIN raw_app.orders AS o ON o.id = ol.order_id
        WHERE p.id = raw_app.inventory_snapshots.product_id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.order_promotions FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.orders AS o
        WHERE o.id = raw_app.order_promotions.order_id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE POLICY tenant_scope ON raw_app.promotions FOR SELECT TO :"raw_role"
USING (
    EXISTS (
        SELECT 1
        FROM raw_app.order_promotions AS op
        JOIN raw_app.orders AS o ON o.id = op.order_id
        WHERE op.promotion_id = raw_app.promotions.id
          AND o.tenant_id = current_setting('app.tenant_id', true)
    )
);

CREATE OR REPLACE VIEW analytics_app.customer_revenue_summary AS
WITH order_rollup AS (
    SELECT
        customer_id,
        count(*) AS order_count,
        min(order_ts)::date AS first_order_date,
        max(order_ts)::date AS most_recent_order_date,
        sum(total_amount) AS gross_revenue,
        avg(total_amount) AS average_order_value
    FROM raw_app.orders
    WHERE status IN ('paid', 'refunded')
    GROUP BY customer_id
),
payment_rollup AS (
    SELECT
        o.customer_id,
        sum(CASE WHEN p.status = 'completed' THEN p.amount ELSE 0 END) AS total_paid_amount,
        count(*) FILTER (WHERE p.status = 'failed') AS failed_payment_count
    FROM raw_app.orders AS o
    JOIN raw_app.payments AS p ON p.order_id = o.id
    GROUP BY o.customer_id
),
review_rollup AS (
    SELECT customer_id, count(*) AS review_count, avg(rating) AS average_rating
    FROM raw_app.reviews
    GROUP BY customer_id
)
SELECT
    c.tenant_id,
    c.id AS customer_id,
    c.full_name AS customer_name,
    c.email,
    cs.name AS segment_name,
    c.acquisition_channel,
    c.signup_date,
    coalesce(o.order_count, 0) AS order_count,
    o.first_order_date,
    o.most_recent_order_date,
    coalesce(o.gross_revenue, 0) AS gross_revenue,
    coalesce(o.average_order_value, 0) AS average_order_value,
    coalesce(p.total_paid_amount, 0) AS total_paid_amount,
    coalesce(p.failed_payment_count, 0) AS failed_payment_count,
    coalesce(r.review_count, 0) AS review_count,
    coalesce(r.average_rating, 0) AS average_rating
FROM raw_app.customers AS c
JOIN raw_app.customer_segments AS cs ON cs.id = c.segment_id
LEFT JOIN order_rollup AS o ON o.customer_id = c.id
LEFT JOIN payment_rollup AS p ON p.customer_id = c.id
LEFT JOIN review_rollup AS r ON r.customer_id = c.id
WHERE c.tenant_id = current_setting('app.tenant_id', true);

CREATE OR REPLACE VIEW analytics_app.daily_sales_summary AS
SELECT
    tenant_id,
    order_ts::date AS order_date,
    count(*) AS order_count,
    sum(total_amount) AS gross_revenue,
    avg(total_amount) AS average_order_value,
    count(*) FILTER (WHERE status = 'cancelled') AS cancelled_order_count,
    count(*) FILTER (WHERE status = 'refunded') AS refunded_order_count
FROM raw_app.orders
WHERE tenant_id = current_setting('app.tenant_id', true)
GROUP BY tenant_id, order_ts::date;

CREATE OR REPLACE VIEW analytics_app.product_sales_summary AS
SELECT
    o.tenant_id,
    p.id AS product_id,
    p.sku,
    p.name AS product_name,
    cat.name AS category_name,
    s.name AS supplier_name,
    sum(ol.quantity) AS units_sold,
    sum(ol.quantity * ol.unit_price - ol.discount_amount) AS net_revenue,
    sum(ol.quantity * (ol.unit_price - ol.unit_cost) - ol.discount_amount) AS gross_margin,
    avg(r.rating) AS average_rating,
    count(r.id) AS review_count
FROM raw_app.order_lines AS ol
JOIN raw_app.orders AS o ON o.id = ol.order_id
JOIN raw_app.products AS p ON p.id = ol.product_id
JOIN raw_app.categories AS cat ON cat.id = p.category_id
JOIN raw_app.suppliers AS s ON s.id = p.supplier_id
LEFT JOIN raw_app.reviews AS r ON r.product_id = p.id AND r.tenant_id = o.tenant_id
WHERE o.tenant_id = current_setting('app.tenant_id', true)
GROUP BY o.tenant_id, p.id, p.sku, p.name, cat.name, s.name;

CREATE OR REPLACE VIEW analytics_app.monthly_product_sales_summary AS
SELECT
    o.tenant_id,
    date_trunc('month', o.order_ts)::date AS order_month,
    p.id AS product_id,
    p.sku,
    p.name AS product_name,
    cat.name AS category_name,
    s.name AS supplier_name,
    count(DISTINCT o.id) AS order_count,
    sum(ol.quantity) AS units_sold,
    sum(ol.quantity * ol.unit_price - ol.discount_amount) AS net_revenue,
    sum(ol.quantity * (ol.unit_price - ol.unit_cost) - ol.discount_amount) AS gross_margin,
    avg(ol.unit_price) AS average_unit_price
FROM raw_app.order_lines AS ol
JOIN raw_app.orders AS o ON o.id = ol.order_id
JOIN raw_app.products AS p ON p.id = ol.product_id
JOIN raw_app.categories AS cat ON cat.id = p.category_id
JOIN raw_app.suppliers AS s ON s.id = p.supplier_id
WHERE o.tenant_id = current_setting('app.tenant_id', true)
GROUP BY o.tenant_id, date_trunc('month', o.order_ts)::date, p.id, p.sku, p.name, cat.name, s.name;

CREATE OR REPLACE VIEW analytics_app.category_performance AS
SELECT
    tenant_id,
    category_name,
    count(DISTINCT product_id) AS product_count,
    sum(units_sold) AS units_sold,
    sum(net_revenue) AS net_revenue,
    sum(gross_margin) AS gross_margin,
    CASE WHEN sum(net_revenue) = 0 THEN 0 ELSE sum(gross_margin) / sum(net_revenue) END AS gross_margin_rate
FROM analytics_app.product_sales_summary
WHERE tenant_id = current_setting('app.tenant_id', true)
GROUP BY tenant_id, category_name;

CREATE OR REPLACE VIEW analytics_app.payment_health_daily AS
SELECT
    o.tenant_id,
    p.payment_ts::date AS payment_date,
    p.payment_method,
    count(*) AS payment_count,
    sum(p.amount) AS payment_amount,
    count(*) FILTER (WHERE p.status = 'failed') AS failed_payment_count,
    CASE WHEN count(*) = 0 THEN 0 ELSE count(*) FILTER (WHERE p.status = 'failed')::numeric / count(*) END AS failed_payment_rate
FROM raw_app.payments AS p
JOIN raw_app.orders AS o ON o.id = p.order_id
WHERE o.tenant_id = current_setting('app.tenant_id', true)
GROUP BY o.tenant_id, p.payment_ts::date, p.payment_method;

CREATE OR REPLACE VIEW analytics_app.fulfillment_health_daily AS
SELECT
    o.tenant_id,
    o.order_ts::date AS order_date,
    s.carrier,
    count(*) AS shipment_count,
    count(*) FILTER (WHERE s.status = 'delayed') AS delayed_shipment_count,
    avg(extract(epoch FROM (s.delivered_ts - s.shipped_ts)) / 86400.0) AS average_delivery_days,
    sum(s.shipping_cost) AS shipping_cost
FROM raw_app.shipments AS s
JOIN raw_app.orders AS o ON o.id = s.order_id
WHERE o.tenant_id = current_setting('app.tenant_id', true)
GROUP BY o.tenant_id, o.order_ts::date, s.carrier;

CREATE OR REPLACE VIEW analytics_app.customer_support_summary AS
SELECT
    tenant_id,
    customer_id,
    count(*) AS ticket_count,
    count(*) FILTER (WHERE status = 'open') AS open_ticket_count,
    count(*) FILTER (WHERE priority IN ('high', 'urgent')) AS high_priority_ticket_count,
    avg(extract(epoch FROM (closed_ts - opened_ts)) / 3600.0) AS average_resolution_hours
FROM raw_app.support_tickets
WHERE tenant_id = current_setting('app.tenant_id', true)
GROUP BY tenant_id, customer_id;

CREATE OR REPLACE VIEW analytics_app.executive_kpis AS
SELECT
    d.tenant_id,
    sum(d.gross_revenue) AS gross_revenue,
    sum(d.order_count) AS order_count,
    avg(d.average_order_value) AS average_order_value,
    sum(p.failed_payment_count) AS failed_payment_count,
    avg(p.failed_payment_rate) AS average_failed_payment_rate,
    sum(f.delayed_shipment_count) AS delayed_shipment_count
FROM analytics_app.daily_sales_summary AS d
LEFT JOIN analytics_app.payment_health_daily AS p
  ON p.tenant_id = d.tenant_id
 AND p.payment_date = d.order_date
LEFT JOIN analytics_app.fulfillment_health_daily AS f
  ON f.tenant_id = d.tenant_id
 AND f.order_date = d.order_date
WHERE d.tenant_id = current_setting('app.tenant_id', true)
GROUP BY d.tenant_id;

CREATE TABLE IF NOT EXISTS demo_app.scenario_metrics (
    scenario_name text PRIMARY KEY,
    auth_role text NOT NULL,
    allowed_schema text NOT NULL,
    exposed_relations integer NOT NULL,
    relations_needed_for_top_customers integer NOT NULL,
    example_sql_lines_for_top_customers integer NOT NULL,
    expected_text_to_sql_benefit text NOT NULL
);

TRUNCATE TABLE demo_app.scenario_metrics;
INSERT INTO demo_app.scenario_metrics (
    scenario_name,
    auth_role,
    allowed_schema,
    exposed_relations,
    relations_needed_for_top_customers,
    example_sql_lines_for_top_customers,
    expected_text_to_sql_benefit
)
VALUES
    (
        'raw_complex_tables',
        :'raw_role',
        'raw_app',
        20,
        7,
        72,
        'Harder: model must discover joins, grain, payment status semantics, and one-to-many pre-aggregation.'
    ),
    (
        'analytics_views',
        :'views_role',
        'analytics_app',
        8,
        1,
        12,
        'Easier: model can query business-grain views with stable aliases and fewer joins.'
    );

CREATE TABLE IF NOT EXISTS demo_app.query_workload (
    id text PRIMARY KEY,
    business_question text NOT NULL,
    expected_chart_type text NOT NULL,
    raw_table_count integer NOT NULL,
    view_relation_count integer NOT NULL,
    raw_sql text NOT NULL,
    view_sql text NOT NULL
);

TRUNCATE TABLE demo_app.query_workload;
INSERT INTO demo_app.query_workload (id, business_question, expected_chart_type, raw_table_count, view_relation_count, raw_sql, view_sql)
VALUES
    (
        'top_customers_lifetime_revenue',
        'Return the top 10 customers by lifetime revenue, including name, email, order count, first and most recent order dates, average order value, total paid amount, failed payment count, and review count.',
        'horizontal_bar',
        7,
        1,
        'Use raw_app.customers, raw_app.customer_segments, raw_app.orders, raw_app.payments, and raw_app.reviews with pre-aggregated CTEs before joining back to customers.',
        'SELECT customer_name, email, order_count, first_order_date, most_recent_order_date, average_order_value, total_paid_amount, failed_payment_count, review_count FROM analytics_app.customer_revenue_summary ORDER BY total_paid_amount DESC NULLS LAST LIMIT 10;'
    ),
    (
        'daily_revenue_trend',
        'Show daily revenue and order count for the last 30 days.',
        'time_series',
        1,
        1,
        'Aggregate raw_app.orders by order_ts::date and tenant_id, filtering paid/refunded statuses.',
        'SELECT order_date, order_count, gross_revenue FROM analytics_app.daily_sales_summary WHERE order_date >= current_date - 30 ORDER BY order_date;'
    ),
    (
        'category_margin',
        'Rank categories by gross margin and margin rate.',
        'bar',
        5,
        1,
        'Join raw_app.order_lines, raw_app.orders, raw_app.products, raw_app.categories, and raw_app.suppliers, then aggregate by category.',
        'SELECT category_name, net_revenue, gross_margin, gross_margin_rate FROM analytics_app.category_performance ORDER BY gross_margin DESC LIMIT 10;'
    ),
    (
        'payment_failures',
        'Show failed payment rate by payment method over time.',
        'time_series',
        2,
        1,
        'Join raw_app.payments to raw_app.orders, bucket payment_ts by date, and group by payment_method.',
        'SELECT payment_date, payment_method, payment_count, failed_payment_count, failed_payment_rate FROM analytics_app.payment_health_daily ORDER BY payment_date, payment_method;'
    );

CREATE OR REPLACE VIEW demo_app.text_to_sql_scenario_metrics AS
SELECT
    scenario_name,
    auth_role,
    allowed_schema,
    exposed_relations,
    relations_needed_for_top_customers,
    example_sql_lines_for_top_customers,
    expected_text_to_sql_benefit
FROM demo_app.scenario_metrics
ORDER BY scenario_name;

CREATE OR REPLACE VIEW demo_app.text_to_sql_workload AS
SELECT
    id,
    business_question,
    expected_chart_type,
    raw_table_count,
    view_relation_count,
    raw_sql,
    view_sql
FROM demo_app.query_workload
ORDER BY id;

REVOKE ALL ON SCHEMA public FROM :"raw_role";
REVOKE ALL ON SCHEMA public FROM :"views_role";
REVOKE ALL ON SCHEMA raw_app FROM :"raw_role";
REVOKE ALL ON SCHEMA raw_app FROM :"views_role";
REVOKE ALL ON SCHEMA analytics_app FROM :"raw_role";
REVOKE ALL ON SCHEMA analytics_app FROM :"views_role";
REVOKE ALL ON SCHEMA demo_app FROM :"raw_role";
REVOKE ALL ON SCHEMA demo_app FROM :"views_role";
REVOKE ALL ON ALL TABLES IN SCHEMA raw_app FROM :"raw_role";
REVOKE ALL ON ALL TABLES IN SCHEMA raw_app FROM :"views_role";
REVOKE ALL ON ALL TABLES IN SCHEMA analytics_app FROM :"raw_role";
REVOKE ALL ON ALL TABLES IN SCHEMA analytics_app FROM :"views_role";
REVOKE ALL ON ALL TABLES IN SCHEMA demo_app FROM :"raw_role";
REVOKE ALL ON ALL TABLES IN SCHEMA demo_app FROM :"views_role";

GRANT USAGE ON SCHEMA raw_app TO :"raw_role";
GRANT SELECT ON ALL TABLES IN SCHEMA raw_app TO :"raw_role";

GRANT USAGE ON SCHEMA analytics_app TO :"views_role";
GRANT SELECT ON ALL TABLES IN SCHEMA analytics_app TO :"views_role";

GRANT USAGE ON SCHEMA demo_app TO :"raw_role";
GRANT USAGE ON SCHEMA demo_app TO :"views_role";
GRANT SELECT ON demo_app.text_to_sql_scenario_metrics TO :"raw_role", :"views_role";
GRANT SELECT ON demo_app.text_to_sql_workload TO :"raw_role", :"views_role";

ANALYZE raw_app.tenants;
ANALYZE raw_app.customer_segments;
ANALYZE raw_app.customers;
ANALYZE raw_app.orders;
ANALYZE raw_app.order_lines;
ANALYZE raw_app.payments;
ANALYZE raw_app.shipments;
ANALYZE raw_app.reviews;
ANALYZE raw_app.support_tickets;
ANALYZE raw_app.products;

\echo 'Text-to-SQL demo database initialization complete'
